<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../MyRecipeBook.Communication/MyRecipeBook.Communication.csproj" />
    <ProjectReference Include="/src/Shared/MyRecipeBook.Communication/MyRecipeBook.Communication.csproj"/>
    <ProjectReference Include="/src/Shared/MyRecipeBook.Exceptions/MyRecipeBook.Exceptions.csproj" />
  </ItemGroup>
</Project>
